(require '[vitambo.buffer :as buf])
(require '[vitambo.mode])
(require '[vitambo.editor :as ed])
(require '[vitambo.motion])
(require '[vitambo.operator])
(require '[vitambo.text-object])
(require '[vitambo.search])
(require '[vitambo.command])
(require '[vitambo.dispatch])
(println "All namespaces loaded OK")
